---
- name: Install and Start the service 
  hosts: localhost
  become: false 

  tasks: 
  - name: Install Nginx
    apt:
      name: nginx
      state: present 

  - name: start Nginx
    service:
      name: nginx
      state: started 
      enabled: true

    
